name: 'Issue Link'
on:
  pull_request:
    types:
     - opened

jobs:
  issue-link:
    runs-on: ubuntu-latest
    steps:
      - uses: tkt-actions/add-issue-links@v1.2.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          branch-prefix: 'issue-'
          position: 'bottom'
          resolve: 'true'
